
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x1d\xb1T\x7fcH=Jj<+\xdfj\x99Wy'
    
_lr_action_items = {'UPTO':([78,],[80,]),'USE':([0,2,3,4,5,7,11,15,52,69,75,79,],[1,-4,-3,1,-5,-2,-1,-6,-9,-10,-33,-34,]),'LPAREN':([21,23,60,],[27,29,73,]),'GENERIC':([17,],[21,]),'NUMBER':([73,80,81,],[78,82,83,]),'ENTITY':([0,2,3,4,5,7,11,15,30,52,69,75,79,],[6,-4,-3,6,-5,-2,-1,-6,39,-9,-10,-33,-34,]),'ASSIGN_OP':([57,58,59,60,84,85,],[-30,72,-28,-29,-32,-31,]),'PORT':([17,22,61,],[23,23,-13,]),'INOUT':([49,],[63,]),'RPAREN':([32,33,34,35,38,56,57,58,59,60,68,74,77,82,83,84,85,],[-15,-16,47,48,-21,-14,-30,-17,-28,-29,-20,-22,-18,84,85,-32,-31,]),'SEMICOLON':([9,19,20,38,39,40,41,42,44,47,48,53,57,59,60,71,74,76,84,85,],[15,-7,-8,51,52,54,-37,-38,-39,61,62,69,-30,-28,-29,75,-22,79,-32,-31,]),'COLON':([33,36,37,67,],[46,49,-24,-23,]),'COMMA':([32,33,37,57,58,59,60,77,84,85,],[45,-16,50,-30,-17,-28,-29,-18,-32,-31,]),'BIT':([46,63,64,65,66,],[59,-27,-25,59,-26,]),'DECIMAL':([9,10,19,20,],[14,16,-7,-8,]),'OUT':([49,],[66,]),'END':([24,25,28,43,54,62,70,],[30,-12,-11,55,-36,-19,-35,]),'IS':([12,26,],[17,31,]),'type_decl':([31,54,],[41,41,]),'IN':([49,],[64,]),'ID':([1,6,8,14,16,18,27,29,31,39,45,46,50,51,54,63,64,65,66,71,72,],[10,12,13,19,20,26,33,37,44,53,33,60,37,37,44,-27,-25,60,-26,76,77,]),'OF':([13,],[18,]),'DOWNTO':([78,],[81,]),'ARCHITECTURE':([0,2,3,4,5,7,11,15,52,55,69,75,79,],[8,-4,-3,8,-5,-2,-1,-6,-9,71,-10,-33,-34,]),'procedure_definition':([31,54,],[42,42,]),'$end':([2,3,4,5,7,11,15,52,69,75,79,],[-4,-3,0,-5,-2,-1,-6,-9,-10,-33,-34,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bit_vector':([46,65,],[57,57,]),'generic_decl':([17,],[22,]),'generic_stmts':([27,45,],[34,56,]),'portdir':([49,],[65,]),'arch_expressions':([31,54,],[40,40,]),'portlist':([29,51,],[35,68,]),'portnames':([29,50,51,],[36,67,36,]),'generic_stmt':([27,45,],[32,32,]),'library':([1,],[9,]),'entity':([0,4,],[2,2,]),'header':([0,4,],[3,3,]),'entity_body':([17,],[24,]),'design':([0,],[4,]),'architecture':([0,4,],[5,5,]),'porttype':([46,65,],[58,74,]),'architecture_body':([31,54,],[43,70,]),'ports':([17,22,],[25,28,]),'unit':([0,4,],[7,11,]),'portdecl':([29,51,],[38,38,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> design","S'",1,None,None,None),
  ('design -> design unit','design',2,'p_design','/home/dilawar/Works/github/pyghdl/language/vhdl.py',97),
  ('design -> unit','design',1,'p_design','/home/dilawar/Works/github/pyghdl/language/vhdl.py',98),
  ('unit -> header','unit',1,'p_unit','/home/dilawar/Works/github/pyghdl/language/vhdl.py',101),
  ('unit -> entity','unit',1,'p_unit','/home/dilawar/Works/github/pyghdl/language/vhdl.py',102),
  ('unit -> architecture','unit',1,'p_unit','/home/dilawar/Works/github/pyghdl/language/vhdl.py',103),
  ('header -> USE library SEMICOLON','header',3,'p_header','/home/dilawar/Works/github/pyghdl/language/vhdl.py',107),
  ('library -> library DECIMAL ID','library',3,'p_library','/home/dilawar/Works/github/pyghdl/language/vhdl.py',110),
  ('library -> ID DECIMAL ID','library',3,'p_library','/home/dilawar/Works/github/pyghdl/language/vhdl.py',111),
  ('entity -> ENTITY ID IS entity_body END ENTITY SEMICOLON','entity',7,'p_entity','/home/dilawar/Works/github/pyghdl/language/vhdl.py',114),
  ('entity -> ENTITY ID IS entity_body END ENTITY ID SEMICOLON','entity',8,'p_entity','/home/dilawar/Works/github/pyghdl/language/vhdl.py',115),
  ('entity_body -> generic_decl ports','entity_body',2,'p_entity_body','/home/dilawar/Works/github/pyghdl/language/vhdl.py',119),
  ('entity_body -> ports','entity_body',1,'p_entity_body','/home/dilawar/Works/github/pyghdl/language/vhdl.py',120),
  ('generic_decl -> GENERIC LPAREN generic_stmts RPAREN SEMICOLON','generic_decl',5,'p_generic_decl','/home/dilawar/Works/github/pyghdl/language/vhdl.py',124),
  ('generic_stmts -> generic_stmt COMMA generic_stmts','generic_stmts',3,'p_generic_stmts','/home/dilawar/Works/github/pyghdl/language/vhdl.py',127),
  ('generic_stmts -> generic_stmt','generic_stmts',1,'p_generic_stmts','/home/dilawar/Works/github/pyghdl/language/vhdl.py',128),
  ('generic_stmt -> ID','generic_stmt',1,'p_generic_stmt','/home/dilawar/Works/github/pyghdl/language/vhdl.py',132),
  ('generic_stmt -> ID COLON porttype','generic_stmt',3,'p_generic_stmt','/home/dilawar/Works/github/pyghdl/language/vhdl.py',133),
  ('generic_stmt -> ID COLON porttype ASSIGN_OP ID','generic_stmt',5,'p_generic_stmt','/home/dilawar/Works/github/pyghdl/language/vhdl.py',134),
  ('ports -> PORT LPAREN portlist RPAREN SEMICOLON','ports',5,'p_ports','/home/dilawar/Works/github/pyghdl/language/vhdl.py',138),
  ('portlist -> portdecl SEMICOLON portlist','portlist',3,'p_portlist','/home/dilawar/Works/github/pyghdl/language/vhdl.py',141),
  ('portlist -> portdecl','portlist',1,'p_portlist','/home/dilawar/Works/github/pyghdl/language/vhdl.py',142),
  ('portdecl -> portnames COLON portdir porttype','portdecl',4,'p_portdecl','/home/dilawar/Works/github/pyghdl/language/vhdl.py',146),
  ('portnames -> ID COMMA portnames','portnames',3,'p_portnames','/home/dilawar/Works/github/pyghdl/language/vhdl.py',149),
  ('portnames -> ID','portnames',1,'p_portnames','/home/dilawar/Works/github/pyghdl/language/vhdl.py',150),
  ('portdir -> IN','portdir',1,'p_portdir','/home/dilawar/Works/github/pyghdl/language/vhdl.py',154),
  ('portdir -> OUT','portdir',1,'p_portdir','/home/dilawar/Works/github/pyghdl/language/vhdl.py',155),
  ('portdir -> INOUT','portdir',1,'p_portdir','/home/dilawar/Works/github/pyghdl/language/vhdl.py',156),
  ('porttype -> BIT','porttype',1,'p_porttype','/home/dilawar/Works/github/pyghdl/language/vhdl.py',160),
  ('porttype -> ID','porttype',1,'p_porttype','/home/dilawar/Works/github/pyghdl/language/vhdl.py',161),
  ('porttype -> bit_vector','porttype',1,'p_porttype','/home/dilawar/Works/github/pyghdl/language/vhdl.py',162),
  ('bit_vector -> ID LPAREN NUMBER DOWNTO NUMBER RPAREN','bit_vector',6,'p_bit_vector','/home/dilawar/Works/github/pyghdl/language/vhdl.py',165),
  ('bit_vector -> ID LPAREN NUMBER UPTO NUMBER RPAREN','bit_vector',6,'p_bit_vector','/home/dilawar/Works/github/pyghdl/language/vhdl.py',166),
  ('architecture -> ARCHITECTURE ID OF ID IS architecture_body END ARCHITECTURE SEMICOLON','architecture',9,'p_architecture','/home/dilawar/Works/github/pyghdl/language/vhdl.py',170),
  ('architecture -> ARCHITECTURE ID OF ID IS architecture_body END ARCHITECTURE ID SEMICOLON','architecture',10,'p_architecture','/home/dilawar/Works/github/pyghdl/language/vhdl.py',171),
  ('architecture_body -> arch_expressions SEMICOLON architecture_body','architecture_body',3,'p_architecture_body','/home/dilawar/Works/github/pyghdl/language/vhdl.py',175),
  ('architecture_body -> arch_expressions SEMICOLON','architecture_body',2,'p_architecture_body','/home/dilawar/Works/github/pyghdl/language/vhdl.py',176),
  ('arch_expressions -> type_decl','arch_expressions',1,'p_arch_expressions','/home/dilawar/Works/github/pyghdl/language/vhdl.py',179),
  ('arch_expressions -> procedure_definition','arch_expressions',1,'p_arch_expressions','/home/dilawar/Works/github/pyghdl/language/vhdl.py',180),
  ('arch_expressions -> ID','arch_expressions',1,'p_arch_expressions','/home/dilawar/Works/github/pyghdl/language/vhdl.py',181),
]
